apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "appstudio, hacbs"
  name: fbc-related-image-check
spec:
  results:
    - name: HACBS_TEST_OUTPUT
  workspaces:
    - name: workspace
  steps:
    - name: check-related-images
      image: quay.io/redhat-appstudio/hacbs-test:v1.0.11@sha256:acf4e35adfbe16916d400f36b616236d872c2527c7618ffc6758ae930e353668
      workingDir: $(workspaces.workspace.path)/hacbs/$(context.task.name)
      resources:
        limits:
          memory: 4Gi
          cpu: 2
        requests:
          memory: 512Mi
          cpu: 10m
      script: |
        #!/usr/bin/env bash
        set -o pipefail
        source /utils.sh
        FAILEDIMAGES=""
        catalog="$(find $(workspaces.workspace.path)/hacbs/fbc-validation/ -name catalog.yaml)"

        # OPM generates catalog file in a way that yaml file could contain stream of JSON objects
        # thats why we need jq in for this situation, because yq can't parse this file
        # however there is also posibility that catalog.yaml has yaml data in it

        relImgs="$(yq -r '.relatedImages[]?.image' $catalog)"
        if [ $? -ne 0 ]; then
          relImgs="$(jq -r '.relatedImages[]?.image' $catalog)"
          if [ $? -ne 0 ]; then
            echo "Could not get related images, make sure catalog.yaml exists in FBC fragment image and has valid yaml format."
            HACBS_TEST_OUTPUT="$(make_result_json -r FAILURE -f 1)"
            echo "${HACBS_TEST_OUTPUT}" | tee "$(results.HACBS_TEST_OUTPUT.path)"
          exit 0
          fi
        fi

        echo -e "These are related images:\n$relImgs"
        # cycle through those related images and show outputs
        for i in ${relImgs// /}
        do
          if ! skopeo inspect --no-tags "docker://${i}"; then
            echo "Skopeo inspect failed on related image: $i"
            FAILEDIMAGES+="$i, "
          fi
        done
        if [ -z "$FAILEDIMAGES" ]; then
          HACBS_TEST_OUTPUT="$(make_result_json -r SUCCESS -s 1)"
          echo "${HACBS_TEST_OUTPUT}" | tee "$(results.HACBS_TEST_OUTPUT.path)"
        else
          echo "These images failed inspection: $FAILEDIMAGES"
          HACBS_TEST_OUTPUT="$(make_result_json -r FAILURE -f 1)"
          echo "${HACBS_TEST_OUTPUT}" | tee "$(results.HACBS_TEST_OUTPUT.path)"
          exit 0
        fi
